### ISSUE TITLE
Could not find a version of package

### ISSUE THREAD

**Issue by Hai-San** [kporras07/composer-symlinks#5]
after composer require kporras07/composer-symlinks 
[InvalidArgumentException]
  Could not find a version of package kporras07/composer-symlinks matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability.

**Comment by somework** [comment]
Thank you.
Will check =)

**Comment by kporras07** [comment]
I'm sorry I missed this. I hadn't published a release. I just published 1.0 (although I suppose you solved your problem a long time ago)
