### ISSUE TITLE
Does not always copy files when using --no-dev

### ISSUE THREAD

**Issue by mike-potter** [kporras07/composer-symlinks#7]
When doing a `composer install --no-dev` it properly creates the destination directory and copies the files the FIRST time.  But once the destination already existss it does not perform the copy again, so any new files added to the source never appear in the destination.

**Comment by kporras07** [comment]
Hi @mike-potter 
Could you provide steps to reproduce? Please

This is what I'm trying right now and I can't replicate your issue:
- Clone project using composer-symlinks
- composer install --no-dev
- Add files to any folder added to symlinks section
- Run composer install --no-dev

In my environment, new files are now in the destination folder.

Thanks,

**Comment by mike-potter** [comment]
I think it's an issue with handling subfolders.  Here is my entry in the `composer.json` file:
```
"project/modules": "docroot/modules/custom",
```
and here is the `ls` of the source (project/modules):
```
project_core
project_analytics
project_defaults
project_test
```
and after doing a `composer install --no-dev` here is the destination (docroot/modules/custom):
```
project_core
project_defaults
project_test
```
Notice the missing "project_analytics" folder?  That was the folder that was added to the source after the initial `composer install --nodev`.

So maybe try your steps above but in the 3rd step, add a new *folder* to the source.  I will also try this in another project folder to see if it is something specific to this project.

**Comment by mike-potter** [comment]
Hrm, just tried this again this morning and it worked fine.  So not sure what caused this originally.  I'll close this for now and reopen if I can find a way to reproduce it.
